name = "LeanProject"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeanProject"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
	version = "git#v4.21.0"

[[lean_lib]]
name = "LeanProject"
